config/routes.rb
Rails.application.routes.draw do
  get 'topics/show'
  get 'users/show'
  ## GET /about page:
  get "about-us", to: "about#index", as: :about

  ## GET root homepage page:
  root to: "pages#home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  ## Quotes – routes for all of the standard CRUD actions and users can see the quotes they've added:
  resources :quotes do
    collection do
      get :user_quotes
      get :user_favorites
    end

    member do
      ## Routes for favoriting and unfavoriting:
      post 'add_favorite'
      delete 'remove_favorite'

      ## Routes for adding and removing topics:
      post :add_topic
      delete :remove_topic

      ## Routes for upvoting and downvoting:
      post 'upvote'
      post 'downvote'
    end
  end  

  ## Route to a user's profile and settings:
  resources :users, only: [:show, :update] do
    get 'settings', on: :collection
  end

  ## Routes for topics:
  resources :topics, only: [:show, :index]
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/quote.rb
class Quote < ApplicationRecord
    ## Pagination:
    self.per_page = 2

    ## Associations and validations:
    belongs_to :user

    ## Favorites associations:
    has_many :favorites
    has_many :favoriting_users, through: :favorites, source: :user  
    
    ## Topics associations:
    has_many :quotes_topics
    has_many :topics, through: :quotes_topics

    ## Upvotes and downvotes associations:
    has_and_belongs_to_many :upvoted_users, class_name: "User", join_table: :upvotes
    has_and_belongs_to_many :downvoted_users, class_name: "User", join_table: :downvotes

    ## Check whether a quote belongs to a given user:
    def owned_by?(user)
        self.user == user
    end

    validates :content, presence: true
    validates :attribution, presence: true

    ## Custom validation – the `source_link` should only be allowed if `source` is present:
    validate :source_link_requires_source
    
    ## Custom setter and getter methods for topics:
    def topic_names=(names)
        self.topics = names.split(",").map do |name|
            Topic.where(name: name.strip).first_or_create!
        end
    end
    
    def topic_names
        self.topics.map(&:name)
    end    

    ## Methods to add and remove topics by name:
    def add_topic_by_name(name)
        topic = Topic.find_or_create_by(name: name)
        self.topics << topic unless self.topics.include?(topic)
    end
    
    def remove_topic_by_name(name)
        topic = Topic.find_by(name: name)
        self.topics.delete(topic) if topic && self.topics.include?(topic)
    end

    ## Check if a user has upvoted or downvoted a particular quote:
    def upvoted_by?(user)
        self.upvoted_users.include?(user)
    end
    
    def downvoted_by?(user)
        self.downvoted_users.include?(user)
    end
    

    private
    
    def source_link_requires_source
      if source_link.present? && source.blank?
        errors.add(:source_link, "cannot be present without a source")
      end
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :set_quote, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
    #### before_action :authorize_user!, only: [:edit, :update, :destroy]
    before_action :authorize_user!, only: [:edit, :update, :destroy, :add_topic, :remove_topic]

    ## Make sure that only logged-in users can access their quotes:
    before_action :authenticate_user!, only: [:user_quotes]

    def index
        #### @quotes = Quote.all.order(created_at: :desc)
        ## Paginate the quotes:
        @quotes = Quote.paginate(page: params[:page]).order(created_at: :desc)
    end
  
    def show
    end
  
    def new
      @quote = Quote.new
    end
  
    def create
      @quote = Quote.new(quote_params)
      @quote.user = current_user  ## Assign the quote to the Devise current user.
      if @quote.save
        flash[:success] = "Quote was successfully created."
        redirect_to @quote
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @quote.update(quote_params)
        redirect_to @quote, notice: 'Quote was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @quote.destroy
      redirect_to quotes_url, notice: 'Quote was successfully destroyed.'
    end
  
    ## Users can see the quotes they've added:
    def user_quotes
        ## Added pagination:
        @user_quotes = current_user.quotes.paginate(page: params[:page]).order(created_at: :desc)
    end      

    def add_favorite
        favorite = current_user.favorites.build(quote_id: params[:id])
        if favorite.save
          redirect_to request.referrer ||  quotes_path(page: params[:page]), notice: 'Quote added to favorites!'
        else
          redirect_to request.referrer || quotes_path(page: params[:page]), alert: 'Something went wrong... *sad panda*'
        end
    end
      
    def remove_favorite
        favorite = current_user.favorites.find_by(quote_id: params[:id])
        favorite.destroy
        redirect_to request.referrer || quotes_path(page: params[:page]), notice: 'Quote removed from favorites.'
    end      

    ## Methods to add and remove topics from quotes:
    def add_topic
        @quote = Quote.find(params[:id])
        @quote.add_topic_by_name(params[:topic_name])
        redirect_to edit_quote_path(@quote)
    end
    
    def remove_topic
        @quote = Quote.find(params[:id])
        @quote.remove_topic_by_name(params[:topic_name])
        redirect_to edit_quote_path(@quote)
    end

    ## Methods to handle upvotes and downvotes:
    def upvote
        if @quote.upvoted_by?(current_user)
            @quote.upvoted_users.delete(current_user)
        else
            @quote.upvoted_users << current_user
            @quote.downvoted_users.delete(current_user) ## Ensure user can't both upvote and downvote.
        end
        redirect_to request.referrer || quotes_path(page: params[:page])
    end
      
    def downvote
        if @quote.downvoted_by?(current_user)
            @quote.downvoted_users.delete(current_user)
        else
            @quote.downvoted_users << current_user
            @quote.upvoted_users.delete(current_user) ## Ensure user can't both upvote and downvote.
        end
        redirect_to request.referrer || quotes_path(page: params[:page])
    end    

    def user_favorites
        @user = current_user
        ## Fetch favorited quotes to paginate and display the user's favorite quotes:
        @favorite_quotes = @user.favorited_quotes.paginate(page: params[:page]).order(created_at: :desc)
    
        ## Fetch recently voted quotes:
        all_recently_voted_quotes = Quote.joins("LEFT JOIN upvotes ON upvotes.quote_id = quotes.id")
        .joins("LEFT JOIN downvotes ON downvotes.quote_id = quotes.id")
        .where('upvotes.user_id = ? OR downvotes.user_id = ?', @user.id, @user.id)
        .order(updated_at: :desc)
        .distinct
        .limit(10)

        @recently_voted_quotes = all_recently_voted_quotes.paginate(page: params[:recent_votes_page], per_page: 2)
    end    

    private
  
    def set_quote
      @quote = Quote.find(params[:id])
    end
  
    def authorize_user!
      unless current_user.admin? || @quote.owned_by?(current_user)
        redirect_to quotes_path, alert: 'You are not authorized to perform this action.'
      end
    end
  
    def quote_params
        params.require(:quote).permit(:content, :attribution, :source, :source_link, :comment, :topic_names)
    end    
end
  

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: @quote) do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.label :attribution %>
    <%= f.text_field :attribution %>

    <%= f.label :source %>
    <%= f.text_field :source %>

    <%= f.label :source_link %>
    <%= f.text_field :source_link %>

    <%= f.label :comment %>
    <%= f.text_area :comment %>

    <%= f.label :topics %>
    <%= f.text_field :topic_names, value: @quote.topic_names.join(", "), placeholder: "Add topics separated by commas." %>

    <%= f.submit %>
<% end %>

app/views/quotes/edit.html.erb
<h1>Edit Quote</h1>
<%= render 'form' %>

<!-- ## show "+TopicA" or "-TopicB" links based on whether the topic is associated with the quote: -->
<% Topic.all.each do |topic| %>
  <% if @quote.topics.include?(topic) %>
    <%= link_to "-#{topic.name}", remove_topic_quote_path(@quote, topic_name: topic.name), method: :delete %>
  <% else %>
    <%= link_to "+#{topic.name}", add_topic_quote_path(@quote, topic_name: topic.name), method: :post %>
  <% end %>
  <br>
<% end %>

<br>
<%= link_to "Back to All Quotes", quotes_path %>

app/views/quotes/index.html.erb
<h1>All Quotes</h1>

<%= link_to "New Quote", new_quote_path %>
<br>
<br>

<ul>
    <% @quotes.each do |quote| %>
        <li>
            <!-- ## Display the quote: -->
            <%= render 'shared/quote', quote: quote %>
            <br>
            <%= link_to "Show", quote_path(quote) %>
            <!-- ## Conditionally display the Edit and Delete links: -->
            <% if current_user.admin? || quote.owned_by?(current_user) %> |
                <%= link_to "Edit", edit_quote_path(quote) %> |
                <!-- #### GET method delete link now working: <%= button_to "Delete", quote_path(quote), method: :delete, data: { confirm: "Are you sure?" } %> -->
                <%= link_to "Delete", quote_path(quote), method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
        </li>
        <br>
    <% end %>
</ul>

<%= will_paginate(@quotes) %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<!-- ## Display validation errors when uploading quote: -->
<% if @quote.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>
    <ul>
    <% @quote.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @quote.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>
    <ul>
    <% @quote.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form' %>

<%= link_to "Back to All Quotes", quotes_path %>

app/views/quotes/show.html.erb
<br>
<!-- #### <p>“<%= @quote.content %>”</p> -->
<!-- ## Using `.present?` to handle both nil and empty string cases: -->
“<%= @quote.content %>”<br>― <strong><%= @quote.attribution %></strong><% if @quote.source.present? %><% if @quote.source_link.present? %>, <%= link_to @quote.source, @quote.source_link %><% else %>, <%= @quote.source %><% end %><% end %>

<br><br>

<!-- ### TD: Add upvotes/downvotes here: -->
<small>Original poster: <%= @quote.user.display_name %> on <%= @quote.created_at.strftime("%B %d, %Y") %> &nbsp; <% if current_user.favorited_quotes.include?(@quote) %><%= link_to '❤', remove_favorite_quote_path(@quote, page: params[:page]), method: :delete %><% else %><%= link_to '🤍', add_favorite_quote_path(@quote, page: params[:page]), method: :post %><% end %> <%= @quote.favoriting_users.count %></small>
<br>
<small>Original poster comment: <i><%= @quote.comment %></i></small>

<!-- ## Display topics for quote: -->
<br>
<small>Topics:<% @quote.topics.each do |topic| %>
    <%= link_to topic.name, topic_path(topic) %>
<% end %></small>

<br><br>

<% if current_user.admin? || @quote.owned_by?(current_user) %>
    <%= link_to "Edit", edit_quote_path(@quote) %> |
    <!-- #### GET method delete link now working: <%= button_to "Delete", quote_path(@quote), method: :delete, data: { confirm: "Are you sure?" } %> | -->
    <%= link_to "Delete", quote_path(@quote), method: :delete, data: { confirm: "Are you sure?" } %> |
<% end %>
<%= link_to "Back to All Quotes", quotes_path %>

app/views/quotes/user_favorites.html.erb
<h2>Your Favorited Quotes:</h2>

<% if @favorite_quotes.present? %>
    <% @favorite_quotes.each do |quote| %>
        <li>
            <!-- ### TD: Fix CSS to not have tab after bulletpoint (not an issue for other partials). -->
            <%= render 'shared/quote', quote: quote %>
        </li>
        <br>
    <% end %>
    <%= will_paginate @favorite_quotes %>
<% else %>
    <p>You haven't favorited any quotes yet.</p>
<% end %>

<br>
<br>
<h2>Your 10 Most Recently Voted Quotes:</h2>
<ul>
  <% @recently_voted_quotes.each do |quote| %>
    <li>
        <%= render 'shared/quote', quote: quote %>
        <br>
    </li>
  <% end %>
</ul>
<%= will_paginate @recently_voted_quotes, param_name: 'recent_votes_page' %>
<br>

app/views/quotes/user_quotes.html.erb
<h2>Your Quotes</h2>

<ul>
    <% if @user_quotes.present? %>
        <% @user_quotes.each do |quote| %>
            <li>
                <%= render 'shared/quote', quote: quote %>
                <br>
                <%= link_to "Edit", edit_quote_path(quote) %> |
                <%= link_to "Delete", quote_path(quote), method: :delete, data: { confirm: "Are you sure?" } %>
            </li>
            <br>
        <% end %>
    <% else %>
        <p>You haven't added any quotes yet.</p>
    <% end %>
</ul>

<!-- ## Pagination: -->
<%= will_paginate @user_quotes %>
<br>