config/routes.rb
Rails.application.routes.draw do
  get 'topics/show'
  get 'users/show'
  ## GET /about page:
  get "about-us", to: "about#index", as: :about

  ## GET root homepage page:
  root to: "pages#home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  ## Quotes – routes for all of the standard CRUD actions and users can see the quotes they've added:
  resources :quotes do
    collection do
      get :user_quotes
      get :user_favorites
    end

    member do
      ## Routes for favoriting and unfavoriting:
      post 'add_favorite'
      delete 'remove_favorite'

      ## Routes for adding and removing topics:
      post :add_topic
      delete :remove_topic

      ## Routes for upvoting and downvoting:
      post 'upvote'
      post 'downvote'
    end
  end  

  ## Route to a user's profile and settings:
  resources :users, only: [:show, :update] do
    get 'settings', on: :collection
  end

  ## Routes for topics:
  resources :topics, only: [:show, :index]
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :quotes_topics
    has_many :quotes, through: :quotes_topics
    ## Validation to ensure topic names are unique:
    validates :name, uniqueness: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  ## Fetch all topics and display them in the index view:
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.erb
<h1>All Topics</h1>

<ul>
    <% @topics.each do |topic| %>
    <li>
        <%= link_to topic.name, topic_path(topic) %>
        (<%= topic.quotes.count %>)
    </li>
    <% end %>
</ul>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<ul>
  <% @topic.quotes.each do |quote| %>
    <li>
        “<%= quote.content %>”<br>― <strong><%= quote.attribution %></strong><% if quote.source.present? %><% if quote.source_link.present? %>, <%= link_to quote.source, quote.source_link %><% else %>, <%= quote.source %><% end %><% end %>
        <br>
        <small>Posted on <%= quote.created_at.strftime("%B %d, %Y") %> &nbsp; <% if current_user.favorited_quotes.include?(quote) %><%= link_to '❤', remove_favorite_quote_path(quote), method: :delete %><% else %><%= link_to '🤍', add_favorite_quote_path(quote), method: :post %><% end %> <%= quote.favoriting_users.count %></small>
        <br>
        <%= link_to "Edit", edit_quote_path(quote) %> |
        <%= link_to "Delete", quote_path(quote), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
    <br>
  <% end %>
</ul>