config/routes.rb
Rails.application.routes.draw do
  get 'topics/show'
  get 'users/show'
  ## GET /about page:
  get "about-us", to: "about#index", as: :about

  ## GET root homepage page:
  root to: "pages#home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  ## Quotes – routes for all of the standard CRUD actions and users can see the quotes they've added:
  resources :quotes do
    collection do
      get :user_quotes
      get :user_favorites
    end

    member do
      ## Routes for favoriting and unfavoriting:
      post 'add_favorite'
      delete 'remove_favorite'

      ## Routes for adding and removing topics:
      post :add_topic
      delete :remove_topic

      ## Routes for upvoting and downvoting:
      post 'upvote'
      post 'downvote'
    end
  end  

  ## Route to a user's profile and settings:
  resources :users, only: [:show, :update] do
    get 'settings', on: :collection
  end

  ## Routes for topics:
  resources :topics, only: [:show, :index]
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "EA Quotes", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Quotes", quotes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Topics", topics_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <!-- ## Navigate to authentication-related pages: -->
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Welcome, " + current_user.display_name + "!", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Quotes", user_quotes_quotes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Favorites', user_favorites_quotes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Settings", settings_users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <!-- ## Trying logout with GET method instead to debug: -->
            <%= link_to "Logout", destroy_user_session_path, class: "nav-link" %>
            <!-- <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %> -->
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_quote.html.erb
<!-- ## Display the quote: -->
“<%= quote.content %>”
<br>― <strong><%= quote.attribution %></strong><% if quote.source.present? %><% if quote.source_link.present? %>, <%= link_to quote.source, quote.source_link %><% else %>, <%= quote.source %><% end %><% end %>
<br>
<small>
    <!-- Posted by: Matīss Apinis on August 10, 2023   🤍 0 🔼 0 🔽 0 -->
    Posted by: <%= link_to quote.user.display_name, user_path(quote.user) %> on <%= quote.created_at.strftime("%B %d, %Y") %>
    &nbsp; 
    <!-- ## Show favorites: -->
    <% if current_user.favorited_quotes.include?(quote) %>
        <%= link_to '❤', remove_favorite_quote_path(quote, page: params[:page]), method: :delete %>
    <% else %>
        <%= link_to '🤍', add_favorite_quote_path(quote, page: params[:page]), method: :post %>
    <% end %>
    <%= quote.favoriting_users.count %>
    <!-- ## Show upvotes and downvotes: -->
    <% if current_user.upvoted_quotes.include?(quote) %>
        <%= link_to '👍', upvote_quote_path(quote, page: params[:page]), method: :post %>
    <% else %>
        <%= link_to '🔼', upvote_quote_path(quote, page: params[:page]), method: :post %>
    <% end %> 
    <%= quote.upvoted_users.count %>
    <% if current_user.downvoted_quotes.include?(quote) %>
        <%= link_to '👎', downvote_quote_path(quote, page: params[:page]), method: :post %>
    <% else %>
        <%= link_to '🔽', downvote_quote_path(quote, page: params[:page]), method: :post %>
    <% end %> 
    <%= quote.downvoted_users.count %>
</small>
<br>
<!-- ## Display topics for the quote: -->
<small>Topics:<% quote.topics.each do |topic| %>
    <%= link_to topic.name, topic_path(topic) %>
    <% unless topic == quote.topics.last %> | <% end %> <!-- ## Separator between topics unless it's the last topic. -->
<% end %></small>
<br>